### ISSUE TITLE
Not crashing when dividing by zero

### ISSUE THREAD

**Issue by sorenpeter** [rumblesan/improviz#40]
I would be nice if improviz did not crash/close when you happen to divide by zero, i.e. when using a variable, that is sometimes zero (or is this too much to ask for:)

**Comment by rumblesan** [comment]
Hi, sorry for the slow response to your issues but I've been having a bit of a break from coding over the summer. I think this should now be fixed and I'll make sure I've pushed the changes. I'll be a bit more active again now so please raise any other issues as you find them

**Comment by rumblesan** [comment]
think this should be fixed now
