### ISSUE TITLE
random() and noise() functions

### ISSUE THREAD

**Issue by sorenpeter** [rumblesan/improviz#41]
I find myself missing a way of getting random or (perlin)noise-based numbers for making my sketches more organic or chaotic. So that is something i would like to see in improviz.

**Comment by rumblesan** [comment]
sorry, totally missed that you asked this as well. There are the `random` and `randomSeed` functions available currently which may well partly help with what you're after. perlin or other noise would be useful as well, and also shouldn't be too tricky to add.

just noticed that I haven't updated the documentation with the random functions, so I'll get on that tonight
