### ISSUE TITLE
strokeWeight?

### ISSUE THREAD

**Issue by sorenpeter** [rumblesan/improviz#46]
Is it possible to change the weight stroke to something wider than 1px?

**Comment by rumblesan** [comment]
This has been on my wishlist for a while, and I started looking at it but realised that my shader skills needed a fair bit of improvement if I was going to do it that way.

Unfortunately recent versions of OpenGL seem to have deprecated the simple line weight stuff, so the solutions are either to use shaders (possibly easy for someone who knows what they're doing) or to actually model geometry wireframes and scale them appropriately (possibly a lot of faffy work I suspect)

**Comment by rumblesan** [comment]
This is now available using the new materials functionality, though it's going to change the way wireframes work, so need to document and test things out a bit

**Comment by rumblesan** [comment]
Considering this to be sorted now so closing
