### ISSUE TITLE
Mac OSX troubleshooting

### ISSUE THREAD

**Issue by Etol1LC** [rumblesan/improviz#55]
Just tried to run the 'improviz' command from terminal on Catalina 10.15.

This is what I get (Pre-built Binary download):

Last login: Thu Sep 10 15:23:29 on ttys000
claudiodonaggio@MacBook-Pro-di-Claudio ~ % cd desktop 
claudiodonaggio@MacBook-Pro-di-Claudio desktop % cd improviz-osx
claudiodonaggio@MacBook-Pro-di-Claudio improviz-osx % improviz
zsh: command not found: improviz
claudiodonaggio@MacBook-Pro-di-Claudio improviz-osx % 

instead, if I double click on the improviz executable, I get: 

Last login: Thu Sep 10 15:28:42 on ttys000
/Users/claudiodonaggio/Desktop/improviz-osx/improviz ; exit;
claudiodonaggio@MacBook-Pro-di-Claudio ~ % /Users/claudiodonaggio/Desktop/improviz-osx/improviz ; exit;
InvalidYaml (Just (YamlException "Yaml file not found: ./improviz.yaml"))
2020-09-10 13:30:.532323  INFO: Running at 640 by 480
2020-09-10 13:30:.532577  INFO: Framebuffer 1280 by 960
2020-09-10 13:30:.532729 ERROR: YAML exception:
Yaml file not found: ./textures/config.yaml
2020-09-10 13:30:.532802  INFO: Loaded 0 texture files
2020-09-10 13:30:.556727  INFO: Loaded 0 material files
2020-09-10 13:30:.556855 ERROR: YAML exception:
Yaml file not found: ./materials/config.yaml
2020-09-10 13:30:.556968 ERROR: YAML exception:
Yaml file not found: ./geometries/config.yaml
2020-09-10 13:30:.557035  INFO: Loaded 0 geometry files
2020-09-10 13:30:.557084  INFO: *****************************
2020-09-10 13:30:.557137  INFO: Creating Improviz Environment
2020-09-10 13:30:.557219  INFO: Improviz HTTP server listening on port 3000
2020-09-10 13:30:.557314  INFO: Improviz resolution: 640 by 480

In this case the white screen on the top left corner opens up, but as the .yaml file did not charge, nothing will happen when I try to send code (either from the editor or from the atom plug in).

Any idea how can I fix it?? Thanx!

**Comment by rumblesan** [comment]
Hi @Etol1LC 
so the issue is that in the terminal if you just run `improviz` then OSX is going to try and find the executable in it's `$PATH` but it's not actually there. To run improviz you have to tell it that you want to run the executable that's inside the folder you're in, so you need to add a `./` to be beginning.
so run `./improviz`

I've just re-read the startup docs and realised that this wasn't actually made clear, so sorry for that.

let me know if that works for you, and I'll update the docs

**Comment by rumblesan** [comment]
So I've updated the getting started documentation so that it's hopefully a bit more understandable and clear.
https://improviz.rumblesan.com/getting-started.html
Let me know if you still have any issues, or if you feel the docs are still not as good as you'd hope :)

**Comment by Etol1LC** [comment]
Hi @rumblesan! Thanks you for your kind reply. It is now working
beautifully. It's awesome!!
I will definitely let you know if I get stuck or have anything I will not
understand.
Thanks for your help!

Il sab 12 set 2020, 15:07 Guy John <notifications@github.com> ha scritto:
