### ISSUE TITLE
Support/discussion channel

### ISSUE THREAD

**Issue by hellocatfood** [rumblesan/improviz#61]
The Toplap rocket chat service is likely to be shut down soon https://chat.toplap.org/channel/announcements?msg=hMWMfQkA7hF2FaQnt

Should a dedicate improviz support channel be set up somewhere? Either discourse or discord perhaps?

**Comment by rumblesan** [comment]
I think the discord channel on the toplap server makes the most sense. Can update the readme and docs here to point to it once it's been created.
I've not yet figured out how to create it though :D

**Comment by rumblesan** [comment]
Right, got the channel, and I've put something in the readme.

not clear to me how I can create a permanent invite link, or if that's even a thing on discord but can figure that out.

**Comment by hellocatfood** [comment]
I think the link you created is only valid for seven days...

**Comment by rumblesan** [comment]
yeah that was it, I couldn't find a way to create a long lived invitation link. I guess that's just how discord works 🤷 

just mentioned it in the readme and said to ask for an invite which I guess is the best way to handle that?
