### ISSUE TITLE
strokeSize documentation incorrect?

### ISSUE THREAD

**Issue by hellocatfood** [rumblesan/improviz#65]
In the reference code for strokeSize (https://improviz.rumblesan.com/reference.html ), the strokeSize of 0.3 on a sphere produces a line so thin it can barely be seen. 

![Screenshot from 2021-11-30 11-04-29](https://user-images.githubusercontent.com/151947/144036047-6f59b20e-ce16-48b5-ab51-4c19f9e5648c.png)

The documentation then says that setting it to 0.5 would cover the entire face of the shape, which isn't true in the case of sphere or cube

![Screenshot from 2021-11-30 11-07-13](https://user-images.githubusercontent.com/151947/144036420-d2f4aa7a-84de-4a83-9eb3-3d1953f5b40f.png)

![Screenshot from 2021-11-30 11-06-49](https://user-images.githubusercontent.com/151947/144036434-feaa76f9-7574-4eb7-8a3b-6200713c322c.png)

Running improviz on Ubuntu 21.10 with a window size 640x480

**Comment by rumblesan** [comment]
ooohhh, right yeah that's a docs problem. I remember now that after a chat with soren it seemed more sensible to have it work as a percentage.

so

```
strokeSize(100)
sphere(3)
```

will cover the whole face

default value is 8%

I'll fix the docs now
